### ISSUE TITLE
can i use this for single table design? 

### ISSUE THREAD

**Issue by kalib-code** [ArsenyYankovsky/nova-odm#3]
can i use this for single table design?

**Comment by ArsenyYankovsky** [comment]
AFAIK there's nothing that will stop you from doing it. I assume you could define more than one entity with the same table name. Is there something in particular you're concerned about?

**Comment by ArsenyYankovsky** [comment]
Feel free to open a new issue if you encounter a concrete obstacle preventing from using Nova ODM with single-table design.
